In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm


Using TensorFlow backend.


In [0]:
ROOT_PATH = "/content/drive/My Drive/haze_to_lines_dataset/weather_detector_dataset/"

In [0]:
train = pd.read_csv(ROOT_PATH+'wheather.csv')

In [30]:
train_image = []
for i in tqdm(range(train.shape[0])):
    img = image.load_img(ROOT_PATH+'train/'+train['id'][i], target_size=(28,28,3), grayscale=False)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
X = np.array(train_image)



  0%|          | 0/489 [00:00<?, ?it/s]

  3%|▎         | 13/489 [00:00<00:03, 120.53it/s]

  6%|▌         | 28/489 [00:00<00:03, 127.54it/s]

  8%|▊         | 40/489 [00:00<00:03, 125.09it/s]

 11%|█         | 53/489 [00:00<00:03, 125.90it/s]

 14%|█▍        | 69/489 [00:00<00:03, 133.70it/s]

 17%|█▋        | 85/489 [00:00<00:02, 140.56it/s]

 21%|██        | 101/489 [00:00<00:02, 144.95it/s]

 24%|██▍       | 118/489 [00:00<00:02, 148.87it/s]

 27%|██▋       | 134/489 [00:00<00:02, 150.56it/s]

 31%|███       | 150/489 [00:01<00:02, 151.89it/s]

 34%|███▍      | 166/489 [00:01<00:02, 154.13it/s]

 37%|███▋      | 183/489 [00:01<00:01, 156.56it/s]

 41%|████      | 199/489 [00:01<00:01, 155.21it/s]

 44%|████▍     | 215/489 [00:01<00:01, 155.30it/s]

 47%|████▋     | 231/489 [00:01<00:01, 156.39it/s]

 51%|█████     | 247/489 [00:01<00:01, 152.22it/s]

 54%|█████▍    | 263/489 [00:01<00:01, 145.94it/s]

 58%|█████▊    | 282/489 [00:01<00:01, 156.79it/s]

 71%|███████   | 347/489 [0

In [0]:
y=train['target'].values
y = to_categorical(y)

In [50]:
y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [0]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))

In [0]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [0]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

In [48]:
prediction = model.predict_classes(X_test)
prediction

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [49]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [45]:
!pip install -q h5py pyyaml
!pip install -q tf_nightly

     |████████████████████████████████| 110.8MB 1.2MB/s 
     |████████████████████████████████| 512kB 74.5MB/s 
     |████████████████████████████████| 3.8MB 53.3MB/s 


In [0]:
model.save(ROOT_PATH+'weather_model.h5')